title: "Nick Nunley"
description: "Software engineer, entrepreneur, cancer researcher, bioinformatician, molecular biologist, musician, mathematics enthusiast, board game enthusiast, and surfer"
url: "https://<your-username>.github.io/PersonalWebsite"
baseurl: "/PersonalWebsite"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
collections:
  slides:
    output: true
    permalink: /slides/:name/