title: "Nick Nunley's Resume"
description: "Cancer researcher, bioinformatician, molecular biologist, musician, mathematics enthusiast, board game enthusiast, and surfer"
url: "https://<your-username>.github.io/PersonalWebsite"
baseurl: "/PersonalWebsite"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
