title: "<strong>Nick Nunley</strong>'s Resume"
description: "A simple online resume"
url: "https://<your-username>.github.io/PersonalWebsite"
baseurl: "/PersonalWebsite"
remote_theme: "LeNPaul/academic"
plugins:
  - jekyll-remote-theme
