menu:
# - {name: 'people', url: '/people'}
# - {name: 'publications', url: '/publications'}
# - {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'skills', url: '/skills'}
- {name: 'contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

skills:
- {name: 'Python programming', url: 'https://www.python.org/'}
- {name: 'R programming', url: 'https://www.r-project.org/'}
- {name: 'Unix programming', url: 'https://en.wikipedia.org/wiki/Unix'}
- {name: 'Machine learning', url: 'https://en.wikipedia.org/wiki/Machine_learning'}
- {name: 'Data science', url: 'https://ischoolonline.berkeley.edu/data-science/what-is-data-science/'}
- {name: 'Statistics', url: 'https://www.stat.uci.edu/what-is-statistics/'}
- {name: 'Pipeline development and applications', url: 'https://www.atlassian.com/devops/devops-tools/devops-pipeline'}
- {name: 'Biomedical experimental design', url: 'https://research.columbia.edu/experimental-design'}
- {name: 'Mammalian cell culture', url: 'https://www.sigmaaldrich.com/US/en/applications/cell-culture-and-cell-culture-analysis/cell-culture-by-cell-type/mammalian-cell-culture?srsltid=AfmBOoqNfdWRiTAuebuPKcAxcWJkYdkFalQdBbfpjtNYYi08uGVlsmf2'}
- {name: 'Immunoblotting', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC2583035/'}
- {name: 'Microscopy and IHC', url: 'https://www.cancer.gov/publications/dictionaries/cancer-terms/def/immunohistochemistry'}
- {name: 'Cellular respirometry', url: 'https://www.med.upenn.edu/robertsonlab/assets/user-content/documents/seahorse-experimentation.pdf'}
- {name: 'Mentorship', url: 'https://www.ncbi.nlm.nih.gov/books/NBK552775/'}

social:
- {icon: 'github', link: 'https://github.com/Nick-Nunley'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/nicholas-nunley/'}
- {icon: 'google', link: 'https://scholar.google.com/citations?hl=en&authuser=1&user=9jHVreoAAAAJ'}
- {icon: 'orcid', link: 'https://orcid.org/0009-0007-2368-1653'}

contacts:
- {name: 'Nicholas Nunley', title: 'Staff Research Associate', department: 'Urology', institution: 'University of California Los Angeles', institution_address: 'Westwood, CA', email: 'nicknunley17@ucla.edu', image: 'assets/img/Poster.jpg'}
