name: Update CV

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 */7 * *"  # every 7 days

permissions:
  contents: write

concurrency:
  group: "update-cv"
  cancel-in-progress: false

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Compute checksum of current markdown
        id: before
        run: |
          if [ -f assets/CV_NickNunley.md ]; then
            md5sum assets/CV_NickNunley.md > old.md5
          else
            echo "no file" > old.md5
          fi

      - name: Run CvExport script
        run: python scripts/CvExport.py

      - name: Compute new checksum
        id: after
        run: |
          md5sum assets/CV_NickNunley.md > new.md5
          echo "changed=false" >> $GITHUB_OUTPUT
          if ! cmp -s old.md5 new.md5; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Clean up temporary md5 files
        if: steps.after.outputs.changed == 'true'
        run: rm -f old.md5 new.md5

      - name: Commit updated CV files
        if: steps.after.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update CV files"
